// <auto-generated />
using System;
using System.Collections.Generic;
using Hap.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hap.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HapDbContext))]
    [Migration("20260723022617_AddInitiativeDetailTracking")]
    partial class AddInitiativeDetailTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hap.Domain.Assessments.Assessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModeratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModeratedByPersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Unmoderated")
                        .HasColumnType("boolean");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("CycleId", "PersonId")
                        .IsUnique();

                    b.ToTable("assessments", (string)null);
                });

            modelBuilder.Entity("Hap.Domain.Assessments.AssessmentScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DimensionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ManagerComment")
                        .HasColumnType("text");

                    b.Property<int?>("ManagerScore")
                        .HasColumnType("integer");

                    b.Property<string>("SelfEvidence")
                        .HasColumnType("text");

                    b.Property<int>("SelfScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DimensionId");

                    b.HasIndex("AssessmentId", "DimensionId")
                        .IsUnique();

                    b.ToTable("assessment_scores", (string)null);
                });

            modelBuilder.Entity("Hap.Domain.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ActorPersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("SubjectPersonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.HasIndex("SubjectPersonId", "At");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Hap.Domain.Cycles.Cycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosesAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ContractorExclusionEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FrameworkVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("OpensAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FrameworkVersionId", "State");

                    b.ToTable("cycles", (string)null);
                });

            modelBuilder.Entity("Hap.Domain.Cycles.CycleInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Excluded")
                        .HasColumnType("boolean");

                    b.Property<string>("ExcludedReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("InvitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("CycleId", "PersonId")
                        .IsUnique();

                    b.ToTable("cycle_invitations", (string)null);
                });

            modelBuilder.Entity("Hap.Domain.Cycles.CycleLateOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GrantedByPersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("GrantedByRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GrantedByPersonId");

                    b.HasIndex("PersonId");

                    b.HasIndex("CycleId", "PersonId")
                        .IsUnique();

                    b.ToTable("cycle_late_overrides", (string)null);
                });

            modelBuilder.Entity("Hap.Domain.Frameworks.Dimension", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("FrameworkVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FrameworkVersionId", "Key")
                        .IsUnique();

                    b.ToTable("dimensions", (string)null);
                });

            modelBuilder.Entity("Hap.Domain.Frameworks.Framework", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("frameworks", (string)null);
                });

            modelBuilder.Entity("Hap.Domain.Frameworks.FrameworkVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FrameworkId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<string>("SourceRef")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FrameworkId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("framework_versions", (string)null);
                });

            modelBuilder.Entity("Hap.Domain.Frameworks.LevelDescriptor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescriptorText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DimensionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DimensionId", "Level")
                        .IsUnique();

                    b.ToTable("level_descriptors", (string)null);
                });

            modelBuilder.Entity("Hap.Domain.Org.BusinessUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DirectorySource")
                        .HasColumnType("text");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOnboarded")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("GroupId");

                    b.ToTable("business_units", (string)null);
                });

            modelBuilder.Entity("Hap.Domain.Org.GroupOrg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId", "Name")
                        .IsUnique();

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("Hap.Domain.Org.OrgOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalValue")
                        .HasColumnType("text");

                    b.Property<string>("OverrideValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("org_overrides", (string)null);
                });

            modelBuilder.Entity("Hap.Domain.Org.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessUnitId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ManagerPersonId")
                        .HasColumnType("uuid");

                    b.Property<bool>("OnLeave")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BusinessUnitId");

                    b.HasIndex("ExternalRef")
                        .IsUnique();

                    b.HasIndex("ManagerPersonId");

                    b.ToTable("people", (string)null);
                });

            modelBuilder.Entity("Hap.Domain.Org.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("portfolios", (string)null);
                });

            modelBuilder.Entity("Hap.Domain.Org.RoleGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BusinessUnitId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GrantedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusinessUnitId");

                    b.HasIndex("PersonId");

                    b.ToTable("role_grants", (string)null);
                });

            modelBuilder.Entity("Hap.Domain.Register.HarrisCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CustomerDeployed")
                        .HasColumnType("boolean");

                    b.Property<bool>("GroupReported")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("harris_categories", (string)null);
                });

            modelBuilder.Entity("Hap.Domain.Register.HarrisStageMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HarrisStage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InternalStage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InternalStage")
                        .IsUnique();

                    b.ToTable("harris_stage_map", (string)null);
                });

            modelBuilder.Entity("Hap.Domain.Register.Initiative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AiDlcLevel")
                        .HasColumnType("integer");

                    b.Property<string>("ApprovalStatus")
                        .HasColumnType("text");

                    b.Property<string>("Approver")
                        .HasColumnType("text");

                    b.Property<Guid>("BusinessUnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByPersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CustomersInProduction")
                        .HasColumnType("integer");

                    b.Property<string>("DataSensitivity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("None");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<List<string>>("DimensionsAdvanced")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("dimensions_advanced");

                    b.Property<List<string>>("FunctionsAffected")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("functions_affected");

                    b.Property<string>("GovernanceNotes")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<string>>("ModelsProviders")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("models_providers")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OversightModel")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerPersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("RagStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<string>>("RegulatoryRelevance")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("regulatory_relevance")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<string>("RiskTier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SponsorPersonId")
                        .HasColumnType("uuid");

                    b.Property<bool>("UsesCogito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<List<string>>("VendorsTools")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("vendors_tools")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.HasKey("Id");

                    b.HasIndex("AiDlcLevel");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RiskTier");

                    b.HasIndex("BusinessUnitId", "CurrentStage");

                    b.ToTable("initiatives", (string)null);
                });

            modelBuilder.Entity("Hap.Domain.Register.InitiativeNRLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountUsd")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InitiativeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Recurrence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ReferencedBySubmissionLineId")
                        .HasColumnType("uuid");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.ToTable("initiative_nr_lines", (string)null);
                });

            modelBuilder.Entity("Hap.Domain.Register.InitiativeStageHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EnteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EnteredBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InitiativeId")
                        .HasColumnType("uuid");

                    b.Property<string>("PriorStage")
                        .HasColumnType("text");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.HasIndex("InitiativeId", "EnteredAt");

                    b.ToTable("initiative_stage_history", (string)null);
                });

            modelBuilder.Entity("Hap.Domain.Register.InitiativeWeeklyUpdate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InitiativeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("RagStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.HasIndex("InitiativeId", "CreatedAt");

                    b.ToTable("initiative_weekly_updates", (string)null);
                });

            modelBuilder.Entity("Hap.Domain.Rollups.RollupSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CalibrationDelta")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("CompletionDenominator")
                        .HasColumnType("integer");

                    b.Property<double>("CompletionPct")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uuid");

                    b.Property<string>("FloorLevelDistribution")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("N")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OrgNodeRef")
                        .HasColumnType("uuid");

                    b.Property<string>("OrgNodeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PerDimensionMean")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("Suppressed")
                        .HasColumnType("boolean");

                    b.Property<string>("SuppressionReason")
                        .HasColumnType("text");

                    b.Property<double>("UnmoderatedPct")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CycleId", "OrgNodeType", "OrgNodeRef")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("CycleId", "OrgNodeType", "OrgNodeRef"), false);

                    b.ToTable("rollup_snapshots", (string)null);
                });

            modelBuilder.Entity("Hap.Domain.Assessments.Assessment", b =>
                {
                    b.HasOne("Hap.Domain.Cycles.Cycle", null)
                        .WithMany()
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hap.Domain.Org.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hap.Domain.Assessments.AssessmentScore", b =>
                {
                    b.HasOne("Hap.Domain.Assessments.Assessment", null)
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hap.Domain.Frameworks.Dimension", null)
                        .WithMany()
                        .HasForeignKey("DimensionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hap.Domain.Cycles.Cycle", b =>
                {
                    b.HasOne("Hap.Domain.Frameworks.FrameworkVersion", null)
                        .WithMany()
                        .HasForeignKey("FrameworkVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hap.Domain.Cycles.CycleInvitation", b =>
                {
                    b.HasOne("Hap.Domain.Cycles.Cycle", null)
                        .WithMany()
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hap.Domain.Org.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hap.Domain.Cycles.CycleLateOverride", b =>
                {
                    b.HasOne("Hap.Domain.Cycles.Cycle", null)
                        .WithMany()
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hap.Domain.Org.Person", null)
                        .WithMany()
                        .HasForeignKey("GrantedByPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hap.Domain.Org.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hap.Domain.Frameworks.Dimension", b =>
                {
                    b.HasOne("Hap.Domain.Frameworks.FrameworkVersion", null)
                        .WithMany()
                        .HasForeignKey("FrameworkVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hap.Domain.Frameworks.FrameworkVersion", b =>
                {
                    b.HasOne("Hap.Domain.Frameworks.Framework", null)
                        .WithMany()
                        .HasForeignKey("FrameworkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hap.Domain.Frameworks.LevelDescriptor", b =>
                {
                    b.HasOne("Hap.Domain.Frameworks.Dimension", null)
                        .WithMany()
                        .HasForeignKey("DimensionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hap.Domain.Org.BusinessUnit", b =>
                {
                    b.HasOne("Hap.Domain.Org.GroupOrg", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hap.Domain.Org.GroupOrg", b =>
                {
                    b.HasOne("Hap.Domain.Org.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hap.Domain.Org.OrgOverride", b =>
                {
                    b.HasOne("Hap.Domain.Org.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hap.Domain.Org.Person", b =>
                {
                    b.HasOne("Hap.Domain.Org.BusinessUnit", null)
                        .WithMany()
                        .HasForeignKey("BusinessUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hap.Domain.Org.Person", null)
                        .WithMany()
                        .HasForeignKey("ManagerPersonId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Hap.Domain.Org.RoleGrant", b =>
                {
                    b.HasOne("Hap.Domain.Org.BusinessUnit", null)
                        .WithMany()
                        .HasForeignKey("BusinessUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Hap.Domain.Org.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hap.Domain.Register.Initiative", b =>
                {
                    b.HasOne("Hap.Domain.Org.BusinessUnit", null)
                        .WithMany()
                        .HasForeignKey("BusinessUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hap.Domain.Register.HarrisCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hap.Domain.Register.InitiativeNRLine", b =>
                {
                    b.HasOne("Hap.Domain.Register.Initiative", null)
                        .WithMany()
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hap.Domain.Register.InitiativeStageHistory", b =>
                {
                    b.HasOne("Hap.Domain.Register.Initiative", null)
                        .WithMany()
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hap.Domain.Register.InitiativeWeeklyUpdate", b =>
                {
                    b.HasOne("Hap.Domain.Register.Initiative", null)
                        .WithMany()
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Hap.Domain.Rollups.RollupSnapshot", b =>
                {
                    b.HasOne("Hap.Domain.Cycles.Cycle", null)
                        .WithMany()
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
