#!/usr/bin/env bash
# Regenerates docs/backlog/board.md (status × wave view) from story frontmatter.
# board.md is a VIEW, never a source — hand-editing it is drift (CLAUDE.md §3).
set -euo pipefail
cd "$(dirname "$0")/.."

out=docs/backlog/board.md
mkdir -p docs/backlog

field() { # field <name> <file> — first frontmatter scalar, comment-stripped
  awk -v k="$2" -F': ' '$1==k {sub(/#.*/,""); sub(/^[^:]*: /,""); gsub(/^[ \t]+|[ \t]+$/,""); print; exit}' "$1"
}

{
  echo "# Backlog board — status × wave"
  echo
  echo "_Generated by \`scripts/board.sh\` at $(date -u +%FT%TZ). Do not hand-edit._"
  for status in in-progress qa blocked todo done; do
    echo
    echo "## ${status}"
    echo
    echo "| Story | Title | Epic | Wave | Risk | Estimate |"
    echo "|---|---|---|---|---|---|"
    # sort numerically by story number
    for f in $(ls docs/backlog/HAP-*.md 2>/dev/null | sort -t- -k2 -n); do
      st=$(field "$f" status)
      [ "$st" = "$status" ] || continue
      printf '| %s | %s | %s | %s | %s | %s |\n' \
        "$(field "$f" id)" "$(field "$f" title)" "$(field "$f" epic)" \
        "$(field "$f" wave)" "$(field "$f" risk)" "$(field "$f" estimate)"
    done
  done
} > "$out"

echo "wrote $out"
