/**
 * Externalised UI strings (FR-067). No user-facing copy is written as a literal
 * inside a component — the shell reads every visible string from here, and the
 * strings-guard test enforces it. A future i18n story swaps this module behind a
 * locale selector without touching component code.
 */
export const en = {
  appName: 'HIG AI Adoption Platform',
  appShortName: 'HAP',
  shell: {
    primaryNav: 'Primary',
    signedInAs: 'Signed in as',
    rolePlaceholder: 'Platform Admin',
    skipToContent: 'Skip to main content',
  },
  nav: {
    dashboard: 'Dashboard',
    selfAssessment: 'Self-Assessment',
    managerReview: 'Manager Review',
    register: 'Initiative Register',
    submissions: 'Harris Submissions',
    admin: 'Admin',
  },
  signIn: {
    title: 'Sign in',
    subtitle: 'Local dev provider — choose a seeded role to continue. No password.',
    loading: 'Loading available users…',
    loadError: 'Could not load the sign-in list. Is the API running?',
    signInError: 'Sign-in failed. Please try again.',
    signInAsPrefix: 'Sign in as',
  },
  assessment: {
    breadcrumb: 'Maturity assessment',
    pageTitle: 'Self-assessment',
    loading: 'Loading your self-assessment…',
    loadError: 'Could not load your self-assessment. Is the API running?',
    noOpenCycleTitle: 'No open assessment cycle',
    noOpenCycleBody:
      'There is no assessment cycle open for you to complete right now. Check back when the next cycle opens.',
    purposeLimitation:
      'Purpose: development, not performance management. Pre-populated with your prior scores — a "no change" month takes seconds. Score honestly.',
    dimensionOfTotal: (index: number, total: number): string => `Dimension ${index} of ${total}`,
    levelSetLegend: (dimensionName: string): string => `Select a level for ${dimensionName}`,
    lastMonthLabel: 'Last month',
    lastMonthPill: 'Last month',
    toDoPill: 'To do',
    levelAbbrev: (level: number): string => `L${level}`,
    levelOptionLabel: (level: number, levelName: string): string => `L${level} — ${levelName}`,
    evidenceLabel: 'Evidence / comment (optional, strongly encouraged)',
    evidencePlaceholder: 'What have you seen this month? Links, examples, blockers…',
    evidenceHint: 'Evidence makes manager moderation meaningful and reduces divergence.',
    saveDraft: 'Save draft',
    submitForReview: 'Submit for review',
    submitHint:
        "Your submission is visible to your manager for review. You'll see their moderated scores and comments once complete.",
    progressLabel: 'Progress',
    progressOfTotal: (scored: number, total: number): string => `${scored} of ${total}`,
    progressAnnouncement: (scored: number, total: number): string =>
      `Dimension progress, ${scored} of ${total} scored`,
    progressHintIncomplete: (remaining: number): string =>
      `${remaining} dimension${remaining === 1 ? '' : 's'} still need a score before you can submit.`,
    progressHintComplete: 'All dimensions scored — ready to submit.',
    projectedFloorLabel: 'Projected result',
    floorLevelLabel: 'Floor level',
    floorHeldBy: (dimensionName: string, level: number): string => `held by ${dimensionName} (L${level})`,
    notYetScored: 'Not yet scored',
    saveDraftSuccess: 'Draft saved.',
    saveDraftError: 'Could not save your draft. Please try again.',
    saveDraftLocked: 'This assessment cycle is closed and no longer accepts changes.',
    saveDraftAlreadySubmitted: 'This assessment has already been submitted and can no longer be edited.',
    submitIncomplete: 'Score every dimension before submitting.',
    submitAlreadySubmitted: 'This assessment has already been submitted.',
    submitLocked: 'This assessment cycle is closed and no longer accepts submissions.',
    submitError: 'Could not submit your assessment. Please try again.',
    submittedTitle: 'Assessment submitted',
    submittedBody:
      "Thanks — your self-assessment has been submitted for review. You'll see your manager's moderated scores here once complete.",
    statusIncomplete: (scored: number, total: number): string => `Incomplete · ${scored} of ${total}`,
    statusComplete: 'Complete',
    readOnlyNotice:
      'This assessment cycle is closed. Your scores are shown for reference and can no longer be changed.',
  },
  moderation: {
    breadcrumb: 'Maturity assessment',
    pageTitle: 'Manager review',
    subtitle: (cycleName: string): string => `Moderate self-assessments for your direct reports · Cycle ${cycleName}`,
    loading: 'Loading your review queue…',
    loadError: 'Could not load your review queue. Is the API running?',
    notManagerTitle: 'No direct reports to review',
    notManagerBody: 'You do not currently have any active direct reports to moderate.',
    noReportsTitle: 'Review queue is empty',
    noReportsBody: 'None of your direct reports have an assessment ready to review yet.',
    selectReportPrompt: 'Select a direct report from the review queue to begin.',
    queueComplete: 'All reviews are complete for this cycle.',
    memberLoading: 'Loading this report’s assessment…',
    memberLoadError: 'Could not load this report’s assessment. Is the API running?',
    reportingToYou: 'reporting to you · moderated score becomes score of record',
    onLeaveTag: 'On leave',
    carryForwardToggle: 'Carry forward unchanged dimensions',
    forcedCommentCallout: (count: number): string =>
      `${count} dimension${count === 1 ? '' : 's'} diverge${count === 1 ? 's' : ''} by ≥ 2 levels — a comment is required before you can submit. Self-scores are retained as a calibration-delta signal.`,
    dimensionHeader: 'Dimension',
    selfHeader: 'Self',
    yourScoreHeader: 'Your score',
    divergenceHeader: 'Divergence',
    commentHeader: 'Comment',
    yourScoreLabel: (dimensionName: string): string => `Your score for ${dimensionName}`,
    commentLabel: (dimensionName: string): string => `Comment for ${dimensionName}`,
    commentPlaceholderRequired: 'Comment required (divergence ≥ 2)',
    commentPlaceholderOptional: 'Optional comment',
    commentRequiredError: 'A comment is required when your score diverges from the self-score by 2 or more levels.',
    moderatedDescriptorPrefix: (level: number): string => `Moderated (L${level}):`,
    calibrationDeltaLabel: 'Calibration delta (mean |self − manager|):',
    moderatedFloorLabel: 'moderated floor',
    meanLabel: 'mean',
    saveAndNext: 'Save & next',
    submitModeration: 'Submit moderation',
    saveError: 'Could not save this review. Please try again.',
    saveLocked: 'This assessment cycle is closed and no longer accepts moderation.',
    saveStateError: 'This assessment is not in a state that can be moderated right now.',
    saveValidationError: 'Fix the flagged comments before submitting.',
    saveSuccess: 'Review saved.',
    moderationComplete: 'Moderation submitted — this is now the score of record.',
    readOnlyNotice:
      'This review is read-only: the assessment has already been moderated, or the cycle no longer accepts changes.',
    agreeChip: 'agree',
    divergenceValue: (n: number): string => `Δ ${n}`,
    queueTitle: 'Review queue',
    queueLeft: (count: number): string => `${count} left`,
    queueStateDone: 'done',
    queueStateReviewing: 'reviewing',
    queueStateToDo: 'to do',
    queueFooter: (total: number, moderated: number): string =>
      `${total} direct report${total === 1 ? '' : 's'} · ${moderated} moderated`,
  },
  result: {
    sectionTitle: 'Your moderated result',
    loading: 'Loading your moderated result…',
    intro: 'Your manager has moderated this cycle’s assessment. Moderated scores are the score of record.',
    selfLabel: 'Self:',
    managerLabel: 'Manager:',
    commentLabel: 'Manager comment:',
    noComment: 'No comment provided.',
    dataErased:
      'This cycle’s assessment scores were erased under the data-retention policy (kept for 3 years). ' +
      'The scores are no longer available; aggregate results are retained. You can request a full export of your data.',
  },
  dashboard: {
    breadcrumb: 'Maturity assessment',
    loading: 'Loading the dashboard…',
    loadError: 'Could not load the dashboard. Is the API running?',
    noDataTitle: 'No dashboard available',
    noDataBody:
      'There is no open assessment cycle, or you do not lead a team or unit with an aggregate to show right now.',
    subtitle: (nodeName: string, cycleName: string): string => `Maturity overview · ${nodeName} · Cycle ${cycleName}`,
    liveTag: 'Live — current cycle',
    snapshotTag: 'Closed cycle — frozen snapshot',
    startSelfAssessment: 'Start self-assessment',
    floorLevelLabel: 'Floor level',
    floorLevelHint: 'Weakest-dimension floor (min per person, FR-016)',
    meanMaturityLabel: 'Mean maturity',
    meanMaturityHint: 'Continuous 0–3 mean',
    completionLabel: 'Assessment completion',
    completionHint: (n: number): string => `${n} in the scored population`,
    unmoderatedHint: (pct: number): string => `${pct}% auto-adopted (unmoderated)`,
    overdueLabel: 'Overdue weekly updates',
    stubDash: '—',
    stubPendingRegister: 'Pending the initiative register (a later release)',
    trendUp: (delta: string): string => `▲ +${delta} vs previous cycle`,
    trendDown: (delta: string): string => `▼ −${delta} vs previous cycle`,
    trendFlat: 'No change vs previous cycle',
    trendNone: 'No prior cycle to trend against yet',
    sparklineLabelPrefix: 'Mean maturity trend:',
    dimensionCardTitle: 'Maturity by dimension',
    dimensionCardHint: 'Mean moderated score across the group (0–3)',
    dimensionHeader: 'Dimension',
    meanScoreHeader: 'Mean score',
    valueHeader: 'Value',
    levelHeader: 'Level',
    initiativesHeader: 'Initiatives',
    dimensionBarLabel: (name: string, mean: string): string => `${name}: mean ${mean} of 3`,
    maturityGapCallout: (name: string, mean: string): string =>
      `⚠ ${name} is the weakest dimension (mean ${mean}). Initiative coverage to advance it will appear once the register ships.`,
    pipelineCardTitle: 'Initiative pipeline',
    pipelineStubBody: 'Initiative counts by Harris stage will appear here once the initiative register ships.',
    ideationLabel: 'Ideation',
    developmentLabel: 'Development',
    productionLabel: 'Production',
    stoppedLabel: 'Stopped',
    suppressedTitle: 'Aggregate suppressed',
    suppressedReasonText: (reason: string): string =>
      reason === 'Complement'
        ? 'This group is too small to publish without exposing an individual by comparison (complement suppression).'
        : 'This group is too small to publish (fewer than four people).',
    suppressedCellText: 'Suppressed',
    suppressedCellReason: (reason: string): string => (reason === 'Complement' ? 'complement' : 'n < 4'),
    // Floor-level distribution (FR-016/018) — the honest per-person floor breakdown the KPI shows instead
    // of a rounded mean (BB1). "% at L1+" surfaces a team stuck at L0 that a rounded mean would hide.
    floorBreakdown: (pctAbove: number, pctZero: number): string => `${pctAbove}% at L1+ · ${pctZero}% at L0`,
  },
  register: {
    breadcrumb: 'Initiative register',
    pageTitle: 'AI initiative register',
    subtitle: 'Harris-aligned taxonomy · stage, AI-DLC level and RAG captured per initiative',
    newInitiative: 'New initiative',
    loading: 'Loading the initiative register…',
    loadError: 'Could not load the initiative register. Is the API running?',
    emptyTitle: 'No initiatives to show',
    emptyBody:
      'No initiatives match the current filters. Adjust or clear the filters, or register the first initiative for your BU.',
    // Filters panel
    filtersLabel: 'Filter initiatives',
    searchLabel: 'Search',
    searchPlaceholder: 'Name or description…',
    buLabel: 'BU',
    buAll: 'All BUs',
    categoryLabel: 'Harris category',
    categoryAll: 'All categories',
    stageLabel: 'Stage',
    stageAll: 'All stages',
    ragLabel: 'RAG',
    ragAll: 'Any',
    // Results card
    cardTitle: 'All initiatives',
    resultSummary: (count: number): string => `${count} initiative${count === 1 ? '' : 's'}`,
    staleSummary: (count: number): string => `${count} stale (no update in over 7 days)`,
    sortedNote: 'sorted by last update',
    legendLabel: 'AI-DLC level',
    // Table column headers
    colInitiative: 'Initiative',
    colBu: 'BU',
    colCategory: 'Harris category',
    colStage: 'Stage → Harris',
    colLevel: 'AI-DLC',
    colRag: 'RAG',
    colCustomers: 'Customers',
    colLastUpdate: 'Last update',
    // Cell values
    emptyValue: '—',
    unknownBu: 'Unknown BU',
    unknownCategory: 'Uncategorised',
    stageArrow: (stage: string, harris: string): string => `${stage} → ${harris}`,
    lastUpdateAgo: (days: number): string => (days <= 0 ? 'today' : `${days}d ago`),
    staleFlag: (days: number): string => `${days}d stale`,
    // Enum → display label maps. These are internal state names (not framework/taxonomy content):
    // the wire values ('Idea', 'OnTrack', …) are attribute values; only these labels are shown.
    stageLabels: {
      Idea: 'Idea',
      Evaluation: 'Evaluation',
      Pilot: 'Pilot',
      Production: 'Production',
      Scaled: 'Scaled',
      Retired: 'Retired',
    },
    harrisStageLabels: {
      Ideation: 'Ideation',
      Development: 'Development',
      Production: 'Production',
      IdeasTriedButStopped: 'Stopped',
    },
    ragLabels: {
      OnTrack: 'On Track',
      AtRisk: 'At Risk',
      OffTrack: 'Off Track',
    },
    // Pagination (DataTable paginates above 25 rows — DESIGN.md A4)
    paginationStatus: (current: number, total: number): string => `Page ${current} of ${total}`,
    paginationPrev: 'Previous',
    paginationNext: 'Next',
    paginationHint: 'Paginated at more than 25 rows.',
  },
} as const;
